Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-06, with the labels that each got.

#1440 [Changelog] Update for Gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#1442 [Changelog] Update for Sprint 87
  CHANGELOG.md
Labels: documentation

#1441 Updates non-breaking deps
  package.json
  yarn.lock
Labels: dependencies

#1444 [GAPRINDASHVILI] Update ui-components to 1.0.29 for gaprindashvili
  package.json
  yarn.lock
Labels: blocker, bug

#1445 [Changelog] Update for Sprint 88
  CHANGELOG.md
Labels: documentation

#1446 BZ#1589409 - Support for disabling Dashboard
  client/app/components/dashboard/dashboard.component.js
  client/app/core/authorization.config.js
  client/app/core/navigation.service.js
  client/app/core/product-features.constants.json
  client/app/states/dashboard/dashboard.state.js
Labels: bug, gaprindashvili/yes

#1447 [GAPRINDASHVILI] Update ui-components to 1.0.30 for gaprindashvili
  package.json
  yarn.lock
Labels: blocker, dependencies

#1448 [GAPRINDASHVILI] Update gettext catalogs for gaprindashvili update
  client/gettext/po/manageiq-ui-service.pot
Labels: internationalization

#1449 [GAPRINDASHVILI] Update ui-components to 1.0.31
  package.json
  yarn.lock
Labels: dependencies
