Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-05, with the labels that each got.

#1429 [GAPRINDASHVILI] Update ui-components to 1.0.26 for gaprindashvili
  package.json
  yarn.lock
Labels: dependencies

#1430 [GAPRINDASHVILI] [Changelog] Update for gaprindashvili-3 release
  CHANGELOG.md
Labels: documentation

#1433 BZ#1574774 updated custom button dialog url
  client/app/states/services/custom_button_details/custom_button_details.state.js
Labels: bug, gaprindashvili/yes

#1428 chore(dependencies)-bump non-breaking, code cleanup
  client/app/core/config.js
  client/app/core/modal/base-modal-controller.js
  client/app/core/save-modal-dialog/save-modal-dialog.factory.js
  client/app/core/shopping-cart/shopping-cart.component.js
  client/app/core/tag-editor-modal/tag-editor-modal.service.js
  client/app/orders/order-explorer/order-explorer.component.js
  client/app/orders/order-explorer/order-explorer.component.spec.js
  client/app/orders/process-order-modal/process-order-modal.component.js
  client/app/services/detail-reveal/detail-reveal.component.js
  client/app/services/detail-reveal/detail-reveal.component.spec.js
  client/app/services/edit-service-modal/edit-service-modal.component.js
  client/app/services/generic-objects-list/generic-objects-list.component.js
  client/app/services/ownership-service-modal/ownership-service-modal.component.js
  client/app/services/retire-remove-service-modal/retire-remove-service-modal.component.js
  client/app/services/retire-service-modal/retire-service-modal.component.js
  client/app/services/retire-service-modal/retire-service-modal.spec.js
  client/app/shared/confirmation/confirmation.directive.js
  client/app/shared/custom-dropdown/custom-dropdown.component.js
  client/app/shared/pagination/pagination.component.js
  client/app/shared/tagging/tagging.component.js
  client/app/states/catalogs/explorer/explorer.state.js
  client/app/states/error/error.state.js
  client/app/states/orders/details/details.state.js
  client/app/states/services/custom_button_details/custom_button_details.state.js
  client/app/states/services/reconfigure/reconfigure.state.js
  package.json
  yarn.lock
Labels: dependencies

#1434 [FINE] AuthenticationApi factory - fix fine-specific linter issues
  client/app/core/authentication-api.factory.js
Labels: test

#1432 Removes unused angular upgrade deps
  client/app/app.module.ts
  client/app/main.ts
  client/app/polyfills.ts
  client/index.ejs
  config/webpack.dev.js
  package.json
  yarn.lock
Labels: cleanup, dependencies

#1435 Removes outdated badge
  README.md
Labels: documentation

#1437 pf-login - override patternfly login screen background image
  client/app/states/login/_login.sass
Labels: bug

#1439 Removes whitespace that breaks translation
  client/app/services/service-explorer/service-explorer.component.js
Labels: bug, gaprindashvili/yes, internationalization

#1438 Change service dialog api call to match CUI
  client/app/states/catalogs/details/details.state.js
  client/app/states/catalogs/details/details.state.spec.js
Labels: blocker, gaprindashvili/yes
