Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-11, with the labels that each got.

#1488 [GAPRINDASHVILI] [Changelog] Update for Garpindashvili-6
  CHANGELOG.md
Labels: documentation

#1490 [HAMMER] [Changelog] Update for Hammer RC1
  CHANGELOG.md
Labels: documentation

#1489 [Changelog] Update for Sprint 98, G-6, and H-B2
  CHANGELOG.md
Labels: documentation

#1491 [HAMMER] Update ui-components to 1.1.18 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1497 BZ#1650693 If tagging is readonly we should not show the edit dropdown
  client/app/shared/tagging/tagging.component.js
Labels: bug

#1495 Update deps, includes fix for CVE-2018-16469
  package.json
  yarn.lock
Labels: bug, dependencies

#1499 [Changelog] Update for Sprint 99
  CHANGELOG.md
Labels: documentation

#1502 BZ#1653288 Service is getting retired without any confirmation in self service ui
  client/app/services/service-details/service-details.component.js
Labels: bug, hammer/yes

#1501 Update .pot on master to capture a number of untranslated strings
  client/gettext/po/manageiq-ui-service.pot
Labels: bug, hammer/no, internationalization

#1506 BZ#1653193 - Custom buttons - only show button name when the "Display on Button" option is set
  client/app/services/custom-button/custom-button.html
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#1504 [HAMMER] [Changelog] Update for Hammer RC2
  CHANGELOG.md
Labels: documentation

#1505 BZ#1644250 - Added ability for documentation to be dynamically configured
  client/app/core/navigation/navigation-controller.js
  client/app/layouts/application.html
Labels: blocker, bug, gaprindashvili/yes, hammer/yes
