Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-02, with the labels that each got.

#1382 Remove yarn-error.log
  .gitignore
  yarn-error.log
Labels: developer

#1383 Updated UI components version to remedy dialog select issue
  package.json
  yarn.lock
Labels: bug, dependencies, gaprindashvili/yes

#1385 BZ#1544535 - Navigation menu highlighting
  client/app/core/navigation/navigation-controller.js
Labels: blocker, bug, gaprindashvili/yes

#1386 [Changelog] Update for Sprint 79
  CHANGELOG.md
Labels: documentation

#1387 Added numeral dependency
  client/app.js
  package.json
  yarn.lock
Labels: bug, dependencies, gaprindashvili/no

#1371 Refactors deps
  client/app.js
  client/app/services/service-details/service-details.html
  client/app/shared/shared.module.js
  package.json
  yarn.lock
Labels: cleanup, dependencies, enhancement

#1390 Fixed dependency branch for PF timeline
  package.json
Labels: bug, gaprindashvili/no

#1293 Notifications should gated on sui_notification product feature
  client/app/core/event-notifications.service.js
  client/app/core/event-notifications.service.spec.js
Labels: bug, gaprindashvili/yes

#1391 [Changelog] Update for Sprint 80
  CHANGELOG.md
Labels: documentation
