Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-03, with the labels that each got.

#1393 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-2
  CHANGELOG.md
Labels: documentation

#1392 BZ#1549239 Changed how breadcrumb shows up on catalog order page
  client/app/orders/order-explorer/order-explorer.component.js
  client/app/states/catalogs/details/details.html
  client/app/states/catalogs/details/details.state.js
  client/app/states/orders/details/details.html
  client/app/states/orders/explorer/explorer.state.js
Labels: bug, gaprindashvili/yes

#1394 Ensures service details custom buttons collapse to kebab when > 3
  client/app/services/service-details/service-details.component.js
  client/app/services/service-details/service-details.html
Labels: bug, bugzilla needed, enhancement, ux/approved

#1396 Updates nonbreaking deps
  package.json
  yarn.lock
Labels: dependencies

#1395 custom-button-menu component styling remains consistent
  client/app/services/custom-button-menu/custom-button-menu.html
Labels: bug, gaprindashvili/yes

#1388 [GAPRINDASHVILI] Update gettext catalogs for Gaprindashvili update
  client/gettext/po/manageiq-ui-service.pot
Labels: internationalization

#1389 [GAPRINDASHVILI] Update @manageiq/ui-components to 1.0.16 for gaprindashvili
  package.json
  yarn.lock
Labels: blocker, bug, dependencies

#1374 Adds csp to sui
  client/index.ejs
Labels: bugzilla needed, enhancement

#1346 [FINE] BZ#1518017- Dialog fields load values on init
  client/app/core/dialog-field-refresh.service.js
  client/app/shared/dialog-content/dialog-content.html
  client/app/states/catalogs/details/details.state.js
Labels: bug

#1397 [FINE] Addresses travis fail, missing dangling comma
  client/app/shared/custom-dropdown/custom-dropdown.component.js
Labels: bug

#1384 Moved action button to the bottom of the form
  client/app/states/catalogs/details/details.html
Labels: bug, ux/approved

#1398 [GAPRINDASHVILI] Update gaprindashvili to @manageiq/ui-components 1.0.18
  package.json
  yarn.lock
Labels: blocker, bug, dependencies

#1399 ui-comp dialog select/multi-select assumes correct styling
  client/app.js
  package.json
  yarn.lock
Labels: bug, dependencies

#1407 [Changelog] Update for Sprint 81
  CHANGELOG.md
Labels: documentation

#1408 [GAPRINDASHVILI] ui-components: update to 1.0.20
  package.json
  yarn.lock
Labels: blocker, bug, dependencies

#1409 [GAPRINDASHVILI] Update translations for g update
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/es/manageiq-ui-service.po
  client/gettext/po/fr/manageiq-ui-service.po
  client/gettext/po/ja/manageiq-ui-service.po
  client/gettext/po/pt-BR/manageiq-ui-service.po
  client/gettext/po/zh-Hans-CN/manageiq-ui-service.po
Labels: internationalization

#1411 AuthenticationAPI - use base64encode which can deal with UTF8 passwords
  client/app.js
  client/app/core/authentication-api.factory.js
  client/app/core/core.module.js
  package.json
  yarn.lock
Labels: blocker, bug, dependencies, gaprindashvili/yes

#1412 [GAPRINDASHVILI] update @manageiq/ui-components to 1.0.21
  package.json
  yarn.lock
Labels: blocker, dependencies
