Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-09, with the labels that each got.

#1472 Remove window.patternflyVersion
  client/app.js
Labels: cleanup

#1473 Updates nonbreaking deps
  package.json
  yarn.lock
Labels: dependencies

#1474 BZ#1624573 - Fix issue where error message is not displayed for consoles
  client/app/services/consoles.service.js
Labels: bug, gaprindashvili/yes

#1475 BZ#1630119 - Hide revert snapshot button for openstack vm's
  client/app/services/vms/snapshots.component.js
Labels: bug, gaprindashvili/yes

#1476 [GAPRINDASHVILI] Update ui-components to 1.0.35 for gaprindashvili
  package.json
  yarn.lock
Labels: dependencies

#1478 Fixed issue with dialogs not loading on reconfigure
  client/app/states/services/reconfigure/reconfigure.state.js
Labels: bug, gaprindashvili/yes, hammer/yes
