Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-07, with the labels that each got.

#1453 Service retirement should use make retire as a request
  client/app/services/service-details/service-details.component.js
  client/app/services/service-explorer/service-explorer.component.js
  tests/mock/poweroperations/service.json
  tests/mock/services/service1.json
Labels: blocker, bug

#1452 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-4
  CHANGELOG.md
Labels: documentation

#1454 Fix for refresh of dialog fields not being called in some circumstances
  client/app/states/catalogs/details/details.state.js
  client/app/states/catalogs/details/details.state.spec.js
Labels: blocker, bug, gaprindashvili/yes

#1455 BZ#1600043 - Snapshot modal. Add support to hide memory checkbox
  client/app/services/process-snapshots-modal/process-snapshots-modal.html
Labels: bug, gaprindashvili/yes

#1450 Update nonbreaking deps
  package.json
  yarn.lock
Labels: dependencies

#1458 [GAPRINDASHVILI] BZ#1601587 - Fixed issue with dialogs that causes duplicate values
  package.json
  yarn.lock
Labels: bug, dependencies

#1459 Update last retire call to make request
  client/app/services/retire-remove-service-modal/retire-remove-service-modal.component.js
Labels: blocker, bug

#1461 BZ#1601527 - Fixed issue with retire modal coming up blank
  client/app/services/service-explorer/service-explorer.component.js
Labels: bug

#1460 [Changelog] Update for Sprint 90
  CHANGELOG.md
Labels: documentation

#1462 BZ#1602108 - Changed Retire services to a modal instead of confirmation
  client/app/services/services-state.service.js
Labels: enhancement, ux/review

#1465 Updates dependencies
  package.json
  yarn.lock
Labels: bug, dependencies

#1466 [Changelog] Update for Sprint 91
  CHANGELOG.md
Labels: documentation
