Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-10, with the labels that each got.

#1481 [GAPRINDASHVILI] Update ui-components to 1.0.36 for gaprindashvili
  package.json
  yarn.lock
Labels: dependencies

#1480 [HAMMER] Update i18n catalog for hammer
  client/gettext/po/manageiq-ui-service.pot
  client/gettext/zanata.xml
Labels: internationalization

#1482 BZ#1637512-Restore action cable subscription, ensure enablement flag is available
  client/app/core/appliance-info.service.js
  client/app/core/appliance-info.service.spec.js
  client/app/core/authorization.config.js
  client/app/core/event-notifications.service.js
  client/app/states/login/login.state.js
Labels: bug, gaprindashvili/yes, hammer/yes

#1485 [Changelog] Add Sprint 97 and Hammer Beta1 updates
  CHANGELOG.md
Labels: documentation

#1484 BZ# 1642623 - Fix permission related display issues
  client/app/services/resource-details/resource-details.component.js
  client/app/states/catalogs/explorer/explorer.state.js
Labels: bug, gaprindashvili/yes, hammer/yes

#1486 [HAMMER] [Changelog] Hammer Beta2 update
  CHANGELOG.md
Labels: documentation
