Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-08, with the labels that each got.

#1464 [GAPRINDASHVILI] Update ui-componetns to 1.0.33 for Gaprindashvili
  package.json
  yarn.lock
Labels: dependencies

#1467 BZ#1598893 - Updated URL for custom buttons dialogs
  client/app/states/services/custom_button_details/custom_button_details.state.js
Labels: bug, gaprindashvili/yes

#1468 Updates dependencies
  package.json
  yarn.lock
Labels: dependencies

#1469 [Changelog] Update for Sprint 92
  CHANGELOG.md
Labels: documentation
