Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-04, with the labels that each got.

#1413 tolowercase of a null does not end well - breaks service explorer
  client/app/services/service-explorer/service-explorer.component.js
Labels: bug, gaprindashvili/no

#1417 Refactors ansible credentials to be more generic, override with dialog input
  client/app/services/service-details/service-details-ansible.component.js
Labels: blocker, bug, fine/yes, gaprindashvili/yes

#1414 Update nonbreaking deps
  package.json
  yarn.lock
Labels: dependencies, gaprindashvili/no

#1416 Restores listview deafult row click behavior, expanding row content
  client/app/orders/order-explorer/order-explorer.component.js
Labels: bug

#1415 Adds on-close to pf-notification-drawer component
  client/app/core/navigation/navigation-controller.js
  client/app/layouts/application.html
Labels: bug, gaprindashvili/yes, ux/approved

#1410 Fixes disk size misreporting for some disks
  client/app/services/resource-details/resource-details.component.js
Labels: bug, gaprindashvili/yes

#1418 [FINE] Refactors ansible credentials to treat dialog object as override
  client/app/services/service-details/service-details-ansible.component.js
Labels: bug

#1420 [GAPRINDASHVILI] Update ui-components to 1.0.22 for gaprindashvili
  package.json
  yarn.lock
Labels: blocker, dependencies

#1421 Updates nonbreaking deps
  package.json
  yarn.lock
Labels: dependencies

#1423 BZ#1568574 - Fixed issue with custom button details dynamic field refresh
  client/app/states/services/custom_button_details/custom_button_details.state.js
  client/app/states/services/custom_button_details/custom_button_details.state.spec.js
Labels: blocker, bug, gaprindashvili/yes

#1424 [GAPRINDASHVILI] Update @manageiq/ui-components to 1.0.23 for gaprindashvili
  package.json
  yarn.lock
Labels: blocker, dependencies

#1426 [GAPRINDASHVILI] Update ui-components to 1.0.24 for gaprindashvili
  package.json
  yarn.lock
Labels: dependencies
