Repository ManageIQ/manageiq-ui-service, pull requests merged in 2018-12, with the labels that each got.

#1509 [HAMMER] Fix locale names for hammer
  client/gettext/json/available_languages.json
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/es/manageiq-ui-service.po
  client/gettext/po/ja/manageiq-ui-service.po
  client/gettext/po/pt-BR/manageiq-ui-service.po
  client/gettext/po/zh-Hans-CN/manageiq-ui-service.po
Labels: blocker, bug, internationalization

#1510 Unshift the placeholder message rather onto filtered tags
  client/app/shared/tagging/tagging.component.js
  client/app/shared/tagging/tagging.component.spec.js
Labels: blocker, bug, gaprindashvili/yes, hammer/yes

#1511 [GAPRINDASHVILI] [Changelog] Update for Gaprindashvili-7
  CHANGELOG.md
Labels: documentation

#1512 BZ#1653288 - Duplicates retire modal from service explorer in service details view
  client/app/services/retire-remove-service-modal/retire-remove-service-modal.component.js
  client/app/services/service-details/service-details.component.js
Labels: bug, hammer/yes

#1516 Update ui-components to 1.2.1
  package.json
  yarn.lock
Labels: dependencies

#1515 [HAMMER] Update ui-components to 1.1.19 for hammer
  package.json
  yarn.lock
Labels: dependencies
