Repository ManageIQ/manageiq-ui-service, pull requests merged in 2019-01, with the labels that each got.

#1513 BZ#1471301 - Login/nav brand and logo are set by api
  client/app/core/appliance-info.service.js
  client/app/core/appliance-info.service.spec.js
  client/app/core/navigation/navigation-controller.js
  client/app/layouts/application.html
  client/app/states/login/login.html
  client/app/states/login/login.state.js
  client/assets/images/brand.svg
  client/assets/images/login-screen-logo.png
  skin-sample/README.md
  skin-sample/images/brand.svg
  skin-sample/images/login-screen-logo.png
Labels: enhancement

#1518 [Changelog] Update for Hammer-1
  CHANGELOG.md
Labels: documentation

#1519 [Changelog] Update for Sprint 102
  CHANGELOG.md
Labels: documentation

#1522 .travis.yml - remove deprecated jwt token
  .travis.yml
Labels: bug

#1523 Timeline - remove onResize handler when destroying timeline
  client/app/shared/timeline/timeline.component.js
Labels: bug

#1521 Support custom favicons
  client/app/core/appliance-info.service.js
  client/app/core/appliance-info.service.spec.js
  client/app/core/navigation/navigation-controller.js
  client/app/states/login/login.state.js
  client/assets/images/favicon.ico
  client/index.ejs
Labels: enhancement
