Repository ManageIQ/manageiq-ui-service, pull requests merged in 2019-07, with the labels that each got.

#1552 [Changelog] Update for Hammer-8
  CHANGELOG.md
Labels: documentation, hammer/yes

#1556 [HAMMER] Update ui-components to 1.1.29 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1557 Update ui-components to 1.2.8
  package.json
  yarn.lock
Labels: dependencies

#1551 Service detail screen - don't run automate methods
  client/app/services/service-details/service-details.component.js
  client/app/services/services-state.service.js
  client/app/services/services-state.service.spec.js
  docs/howto.md
Labels: bug, hammer/yes

#1558 [HAMMER] Update ui-components to 1.1.30 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1553 Update the VM remote console button to the new unified HTML5 console
  client/app/core/product-features.constants.json
  client/app/services/service-details/service-details.component.js
  client/app/services/service-details/service-details.html
  client/app/services/service-explorer/service-explorer.component.spec.js
  client/app/services/services-state.service.js
  client/app/services/services-state.service.spec.js
Labels: changelog/yes, enhancement, hammer/no

#1560 Update ui-components to 1.2.10
  package.json
  yarn.lock
Labels: dependencies

#1568 [HAMMER] Update ui-components to 1.1.31 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1564 [Changelog] Update for Sprint 116
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#1569 [Changelog] Update for Ivanchuk Beta1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes
