Repository ManageIQ/manageiq-ui-service, pull requests merged in 2019-04, with the labels that each got.

#1535 [HAMMER] Update ui-components to 1.1.21 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1536 Update ui-components to 1.2.4
  package.json
  yarn.lock
Labels: dependencies

#1537 [HAMMER] Update ui-components to 1.1.22 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1539 [Changelog] Update for Hammer-5 release
  CHANGELOG.md
Labels: documentation, hammer/yes

#1540 [HAMMER] Update ui-components to 1.1.23 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1541 [HAMMER] Update ui-components to 1.1.24 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1532 VM details - show provider when available
  client/app/services/resource-details/resource-details.component.js
Labels: bug, hammer/yes

#1531 Fix centos image filename
  client/assets/images/os/os-linux_centos.svg
Labels: bug, hammer/yes
