Repository ManageIQ/manageiq-ui-service, pull requests merged in 2019-08, with the labels that each got.

#1570 Add support for the VMRC remote consoles for VMware VMs
  client/app/core/product-features.constants.json
  client/app/services/consoles.service.js
  client/app/services/service-details/service-details.component.js
  client/app/services/service-details/service-details.html
  client/app/services/service-explorer/service-explorer.component.spec.js
  client/app/services/services-state.service.js
  client/app/services/services-state.service.spec.js
Labels: changelog/yes, hammer/no

#1566 Service detail - don't show custom button for lists
  client/app.js
  client/app/services/custom-button-menu/custom-button-menu.component.js
  client/app/services/custom-button/_custom-button-menu.sass
  client/app/services/custom-button/custom-button-menu.component.spec.js
  client/app/services/custom-button/custom-button-menu.html
  client/app/services/custom-button/custom-button.component.js
  client/app/services/custom-button/custom-button.component.spec.js
  client/app/services/custom-button/custom-button.html
  client/app/services/service-details/service-details.html
  client/app/services/services.module.js
  package.json
  tests/utils/utils.spec.js
  yarn.lock
Labels: bug, hammer/yes, ivanchuk/yes

#1571 Update ui-components to 1.3.0
  package.json
  yarn.lock
Labels: dependencies

#1572 [IVANCHUK] Update ui-components to 1.2.13 for ivanchuk
  package.json
  yarn.lock
Labels: dependencies

#1573 Node 12 compatibility
  package.json
  yarn.lock
Labels: dependencies, ivanchuk/no

#1574 Add missing translate directive
  client/app/states/catalogs/details/details.html
Labels: bug, internationalization, ivanchuk/yes

#1575 Add locale_name to all available catalogs
  client/gettext/json/available_languages.json
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/es-ES/manageiq-ui-service.po
  client/gettext/po/fr/manageiq-ui-service.po
  client/gettext/po/ja/manageiq-ui-service.po
  client/gettext/po/ko/manageiq-ui-service.po
  client/gettext/po/nl/manageiq-ui-service.po
  client/gettext/po/pt-BR/manageiq-ui-service.po
  client/gettext/po/pt-PT/manageiq-ui-service.po
  client/gettext/po/zh-Hans-CN/manageiq-ui-service.po
  client/gettext/po/zh-TW/manageiq-ui-service.po
Labels: internationalization, ivanchuk/no

#1577 [Changelog] Update for Sprint 118
  CHANGELOG.md
Labels: documentation

#1581 Drop GTL switcher from Service Explorer breadcrumbs bar
  client/app/services/service-explorer/service-explorer.component.js
  client/app/services/service-explorer/service-explorer.component.spec.js
  client/app/services/service-explorer/service-explorer.html
  client/app/states/services/resource-details/details.state.js
  client/assets/sass/breadcrumbs.sass
Labels: bug, enhancement, ivanchuk/no

#1578 Add translatable result labels to filter config
  client/app/catalogs/catalog-explorer.component.js
  client/app/orders/order-explorer/order-explorer.component.js
  client/app/services/service-explorer/service-explorer.component.js
  client/app/services/vms/snapshots.component.js
Labels: bug, internationalization, ivanchuk/yes

#1579 Make strings in notification drawer translatable
  client/app/components/notifications/heading.html
  client/app/core/event-notifications.service.js
  client/app/core/navigation/navigation-controller.js
  client/app/layouts/application.html
Labels: bug, internationalization, ivanchuk/yes

#1582 [Changelog] Update for Ivanchuk RC1
  CHANGELOG.md
Labels: documentation, ivanchuk/yes
