Repository ManageIQ/manageiq-ui-service, pull requests merged in 2019-09, with the labels that each got.

#1583 [IVANCHUK] Add translations for ivanchuk
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/es/manageiq-ui-service.po
  client/gettext/po/fr/manageiq-ui-service.po
  client/gettext/po/ja/manageiq-ui-service.po
  client/gettext/po/pt-BR/manageiq-ui-service.po
  client/gettext/po/zh-Hans-CN/manageiq-ui-service.po
Labels: internationalization

#1586 Update ui-components to 1.3.1
  package.json
  yarn.lock
Labels: dependencies

#1585 [IVANCHUK] Update ui-components to 1.2.14 for ivanchuk
  package.json
  yarn.lock
Labels: dependencies

#1584 [HAMMER] Update ui-components to 1.1.33 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1587 [HAMMER] Update ui-components to 1.1.34 for hammer
  package.json
  yarn.lock
Labels: dependencies

#1590 [Changelog] Rollup of Ivanchuk releases
  CHANGELOG.md
Labels: documentation, ivanchuk/yes

#1589 Add check for valid language codes
  language/validate-language-codes.js
  package.json
Labels: developer, internationalization, ivanchuk/yes

#1591 Remove standard js, use eslint
  .eslintignore
  .eslintrc.js
  README.md
  client/app.js
  client/app/core/appliance-info.service.js
  client/app/core/appliance-info.service.spec.js
  client/app/core/config.js
  client/app/core/core.module.js
  client/app/core/gettext.config.js
  client/app/globals.js
  client/app/services/custom-button/custom-button.component.js
  client/app/services/custom-button/custom-button.component.spec.js
  client/app/services/service-details/service-details.component.js
  client/app/services/service-explorer/service-explorer.component.js
  client/app/services/services-state.service.js
  client/app/shared/pagination/pagination.component.js
  client/app/shared/tagging/tagging.component.spec.js
  client/app/shared/timeline/timeline.component.js
  client/console/webmks.js
  config/available-languages.js
  config/webpack.dev.js
  language/index.js
  language/zanata.js
  package.json
  protractor.conf.js
  tests/utils/utils.spec.js
  yarn.lock
Labels: developer

#1592 Snapshots - name & description shown & optional depends on VM type
  client/app/services/process-snapshots-modal/process-snapshots-modal.component.js
  client/app/services/process-snapshots-modal/process-snapshots-modal.html
Labels: bug, ivanchuk/yes

#1593 Fix extraction of "Order # 608000000000012 and all of its service requests will be permanently removed!"
  client/app/orders/process-order-modal/process-order-modal.html
  language/validate.js
Labels: bug, internationalization, ivanchuk/yes

#1594 [EmbeddedAnsible] Fix stdout sanitization
  client/app/services/service-details/service-details-ansible.component.js
Labels: bug, ivanchuk/yes
