Repository ManageIQ/manageiq-ui-service, pull requests merged in 2020-03, with the labels that each got.

#1627 Login - show error message on any failure, not just 401
  client/app/states/login/login.state.js
  client/app/states/login/login.state.spec.js
  yarn.lock
Labels: bug

#1633 [JANSA] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#1632 [IVANCHUK] Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#1631 [JANSA] Update source catalog for jansa
  client/gettext/json/available_languages.json
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/es-ES/manageiq-ui-service.po
  client/gettext/po/fr/manageiq-ui-service.po
  client/gettext/po/ja/manageiq-ui-service.po
  client/gettext/po/manageiq-ui-service.pot
  client/gettext/po/pt-BR/manageiq-ui-service.po
  client/gettext/po/zh-Hans-CN/manageiq-ui-service.po
Labels: internationalization

#1635 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
