Repository ManageIQ/manageiq-ui-service, pull requests merged in 2020-05, with the labels that each got.

#1641 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#1642 [IVANCHUK] Update ui components to 1.2.17
  package.json
  yarn.lock
Labels: dependencies

#1644 Update ui-components to 1.4.0
  package.json
  yarn.lock
Labels: dependencies

#1643 [JANSA] Update ui-components to 1.3.4
  package.json
  yarn.lock
Labels: dependencies, enhancement

#1645 [IVANCHUK] Update ui-components to 1.2.18
  package.json
  yarn.lock
Labels: dependencies

#1647 Update ui-components to 1.4.1
  package.json
  yarn.lock
Labels: dependencies

#1646 [JANSA] Update ui components to 1.3.5
  package.json
  yarn.lock
Labels: dependencies
