Repository ManageIQ/manageiq-ui-service, pull requests merged in 2020-08, with the labels that each got.

#1661 Remove MIQ_SPARTAN in favor of Foreman
  docs/developer_setup.md
Labels: documentation

#1663 Honor 'display' parameter for button groups
  client/app/services/custom-button/custom-button.html
Labels: bug, ivanchuk/yes, jansa/yes?

#1664 Add config file for Transifex
  .tx/config
Labels: internationalization

#1665 [JANSA] Add config file for Transifex
  .tx/config
Labels: developer, internationalization
