Repository ManageIQ/manageiq-ui-service, pull requests merged in 2020-10, with the labels that each got.

#1676 [JANSA] Update npm dependencies
  .babelrc
  .travis.yml
  client/app.js
  client/app/actions/appCounters/appCounters.test.js
  client/app/actions/appCounters/index.js
  client/app/catalogs/catalog-explorer.component.spec.js
  client/app/components/dashboard/dashboard.component.spec.js
  client/app/constants/appCounters.js
  client/app/core/config.js
  client/app/core/core.module.js
  client/app/core/event-notifications.service.spec.js
  client/app/core/navigation.service.js
  client/app/core/navigation/navigation.controller.spec.js
  client/app/core/shopping-cart.service.spec.js
  client/app/core/shopping-cart/shopping-cart.component.spec.js
  client/app/layouts/_application.sass
  client/app/orders/order-explorer/order-explorer.component.spec.js
  client/app/orders/process-order-modal/process-order-modal.component.spec.js
  client/app/orders/request-list/requests-list.component.spec.js
  client/app/reducers/appCounters/appCounters.test.js
  client/app/reducers/appCounters/index.js
  client/app/reducers/index.js
  client/app/services/detail-reveal/detail-reveal.component.spec.js
  client/app/services/resource-details/resource-details.component.spec.js
  client/app/services/service-details/service-details-ansible.component.spec.js
  client/app/services/service-details/service-details.component.spec.js
  client/app/services/service-explorer/service-explorer.component.spec.js
  client/app/services/vms/snapshots.component.spec.js
  client/app/shared/confirmation/confirmation.component.spec.js
  client/app/shared/custom-dropdown/custom-dropdown.component.spec.js
  client/app/shared/elapsedTime.filter.spec.js
  client/app/shared/format-bytes.filter.spec.js
  client/app/shared/icon-status.component.js
  client/app/shared/icon-status.component.spec.js
  client/app/shared/language-switcher/language-switcher.component.spec.js
  client/app/shared/pagination/pagination.component.spec.js
  client/app/shared/substitute.filter.spec.js
  client/app/shared/timeline/timeline.component.spec.js
  client/app/states/catalogs/details/details.state.js
  client/app/states/catalogs/details/details.state.spec.js
  client/app/states/login/login.state.spec.js
  client/app/states/orders/details/details.state.spec.js
  client/app/states/services/custom_button_details/custom_button_details.state.spec.js
  client/app/states/services/details/details.state.spec.js
  client/app/states/services/reconfigure/reconfigure.state.spec.js
  client/app/states/vms/snapshots/snapshots.state.spec.js
  config/webpack.dev.js
  config/webpack.prod.js
  config/webpack.static.js
  config/webpack.testing.js
  karma.conf.js
  package.json
  yarn.lock
Labels: dependencies, technical debt

#1679 [IVANCHUK] Update ui-components to 1.2.23
  package.json
  yarn.lock
Labels: dependencies

#1678 [JANSA] Update ui-components to 1.3.8
  package.json
  yarn.lock
Labels: dependencies

#1677 Update ui-components to 1.4.4
  package.json
  yarn.lock
Labels: dependencies

#1680 Fix webpack manifest paths
  config/manifest.js
  config/webpack.prod.js
Labels: bug, jansa/yes

#1682 Update i18n message catalog
  client/gettext/po/manageiq-ui-service.pot
Labels: internationalization
