Repository ManageIQ/manageiq-ui-service, pull requests merged in 2020-11, with the labels that each got.

#1684 Translations provided on 2020-11-02
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/de/manageiq-ui-service.po
  client/gettext/po/es/manageiq-ui-service.po
  client/gettext/po/fr/manageiq-ui-service.po
  client/gettext/po/it/manageiq-ui-service.po
  client/gettext/po/ja/manageiq-ui-service.po
  client/gettext/po/ko/manageiq-ui-service.po
  client/gettext/po/pt-BR/manageiq-ui-service.po
  client/gettext/po/zh-CN/manageiq-ui-service.po
  client/gettext/po/zh-TW/manageiq-ui-service.po
Labels: enhancement, internationalization, kasparov/yes?

#1685 Updated Japanese Translation File from 2020-11-04
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/ja/manageiq-ui-service.po
Labels: enhancement, internationalization, kasparov/yes?

#1686 Translations provided on 2020-11-17
  client/gettext/json/available_languages.json
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/de/manageiq-ui-service.po
  client/gettext/po/es/manageiq-ui-service.po
  client/gettext/po/fr/manageiq-ui-service.po
  client/gettext/po/it/manageiq-ui-service.po
  client/gettext/po/ko/manageiq-ui-service.po
  client/gettext/po/pt-BR/manageiq-ui-service.po
Labels: bug, internationalization, kasparov/yes?

#1689 drop sudo:false
  .travis.yml
Labels: developer
