Repository ManageIQ/manageiq-ui-service, pull requests merged in 2021-03, with the labels that each got.

#1699 WebMKS: fix mix of common js and import/export
  client/console/common.js
  client/console/webmks.js
Labels: bug

#1701 [LASKER] yarn: lock versions by adding yarn.lock
  .gitignore
  yarn.lock
Labels: dependencies

#1703 Updated Translations from 2021-03-27
  client/gettext/json/manageiq-ui-service.json
  client/gettext/po/pt-BR/manageiq-ui-service.po
Labels: internationalization, lasker/yes?
