Repository ManageIQ/manageiq-ui-service, pull requests merged in 2022-02, with the labels that each got.

#1763 More GitHub Actions changes
  .github/workflows/ci.yaml
  README.md
Labels: developer, test

#1765 Add Build History Graph to README.md
  README.md
Labels: developer, test

#1767 Support the act tool for testing GHA
  .github/workflows/ci.yaml
  bin/before_install
Labels: developer, test

#1711 update node and other versions
  .github/workflows/ci.yaml
  docs/developer_setup.md
  package.json
  yarn.lock
Labels: dependencies

#1773 Downgrade node version to 14
  .github/workflows/ci.yaml
  docs/developer_setup.md
  package.json
Labels: technical debt, najdorf/yes?

#1774 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test

#1775 Temporarily hardcode the novnc version
  config/webpack.dev.js
Labels: bug, najdorf/yes?

#1764 Adjust specs so they work using act
  bin/before_install
  karma.conf.js
Labels: test

#1776 Bump karma to latest to fix security issue
  package.json
  yarn.lock
Labels: security fix
