Repository ManageIQ/manageiq-ui-service, pull requests merged in 2023-04, with the labels that each got.

#1834 Force upgrading node-sass to ^8.0.0
  package.json
  yarn.lock
Labels: wip, dependencies

#1845 Upgrading webpack to latest version
  package.json
  yarn.lock
Labels: bug, security fix

#1846 Revert --openssl-legacy-provider now that we have upgraded webpack
  package.json
Labels: technical debt
