Repository ManageIQ/manageiq-ui-service, pull requests merged in 2023-03, with the labels that each got.

#1831 Locking moment to ~2.29.4
  package.json
  yarn.lock
Labels: security fix

#1832 Removing resolutions
  package.json
  yarn.lock
Labels: technical debt

#1839 Add Native Console Support to Service UI
  client/app/core/product-features.constants.json
  client/app/services/consoles.service.js
  client/app/services/consoles.service.spec.js
  client/app/services/service-details/service-details.component.js
  client/app/services/service-details/service-details.html
  client/app/services/service-explorer/service-explorer.component.spec.js
  client/app/services/services-state.service.js
  client/app/services/services-state.service.spec.js
  client/gettext/po/manageiq-ui-service.pot
  tests/mock/poweroperations/service.json
  tests/mock/poweroperations/vm.json
  tests/mock/rbac/allPermissions.json
  tests/mock/services/service1.json
  tests/mock/services/servicePermissions.json
  tests/mock/session/user.json
Labels: enhancement

#1835 Lock nth-check to ^2.1.1
  package.json
  yarn.lock
Labels: security fix
