Repository ManageIQ/manageiq-ui-service, pull requests merged in 2024-07, with the labels that each got.

#1913 Update d3-color to 3.1.0 using resolution
  package.json
  yarn.lock
Labels: dependencies

#1914 Add a security test that runs yarn npm audit
  .github/workflows/ci.yaml
  .yarnrc.yml
  package.json
Labels: dependencies, security

#1916 [MORPHY] Update webpack cli to 4.10.0
  package.json
  yarn.lock
Labels: bug, dependencies

#1917 [Morphy] Update moment-timezone
  package.json
  yarn.lock
Labels: dependencies, security fix
