Repository ManageIQ/manageiq-ui-service, pull requests merged in 2025-02, with the labels that each got.

#1947 Update the npmAuditExcludePackages due to package updates
  .yarnrc.yml
  Rakefile
Labels: developer

#1948 [Mophy] Update qs
  yarn.lock
Labels: dependencies

#1953 [Morphy] Update trim-newlines
  package.json
  yarn.lock
Labels: dependencies

#1954 [Morphy] Update angular
  yarn.lock
Labels: dependencies

#1950 [Morphy] Update cross spawn
  package.json
  yarn.lock
Labels: dependencies

#1952 [Morphy] Update tar
  package.json
  yarn.lock
Labels: dependencies

#1955 [Morphy] Update moment
  package.json
  yarn.lock
Labels: dependencies

#1957 [Morphy] Update nth check
  package.json
  yarn.lock
Labels: dependencies

#1958 [Morphy] Update ansi regex
  package.json
  yarn.lock
Labels: dependencies

#1959 [Morphy] Update moment
  package.json
  yarn.lock
Labels: dependencies

#1960 Exclude bootstrap-sass from yarn audit
  .yarnrc.yml
Labels: security, spassky/yes
